add support for --timeout flag
sindresorhus/is-online-cli pull request #3
Opened 2017-03-21 22:48 UTC by williamboman

2017-03-22 07:25 UTC, sindresorhus requested changes

2017-03-22 07:25 UTC, sindresorhus commented on cli.js
> +}
Just pass `cli.flags` directly to `isOnline`

2017-03-22 07:25 UTC, sindresorhus commented on cli.js
>  	  ${logSymbols.success} Online
The flag needs to be documented. See how to do it here: https://github.com/sindresorhus/boxen-cli/blob/master/cli.js

Also need to update readme afterwards.

2017-03-22 07:25 UTC, sindresorhus commented on test.js
> +test('should exit with 1 when offline', t => t.throws(shortCircuit()));
I generally don't like using inline arrow functions when it doesn't return anything. Makes the code harder to read.  Wrap the bodies in braces and put them on a new line.

2017-03-22 11:53 UTC, williamboman commented on cli.js
> +}
Do you want me to add support for the `version` option as well (will have to shim it as `--ip-version`)?

2017-03-23 12:50 UTC, sindresorhus commented on cli.js
> +}
Nah. We can add it later if anyone requests it. I don't see much usefulness in it.

2017-04-17 06:26 UTC, sindresorhus approved these changes

2017-04-17 06:26 UTC, merged